# Generated by Django 2.2.3 on 2020-10-16 02:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Area del conocimiento',
                'verbose_name_plural': 'Areas del conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Dirige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo_inv', models.IntegerField()),
                ('id_profesor', models.IntegerField()),
                ('estado_direccion', models.BooleanField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Dirige',
                'verbose_name_plural': 'Dirige',
            },
        ),
        migrations.CreateModel(
            name='GrupoInvestigacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_institucion', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_fundacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Grupo de investigación',
                'verbose_name_plural': 'Grupos de investigación',
            },
        ),
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_area_con', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Linea de investigación',
                'verbose_name_plural': 'Lineas de investigación',
            },
        ),
        migrations.CreateModel(
            name='Maneja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_linea_inv', models.IntegerField()),
                ('id_profesor', models.IntegerField()),
                ('estado_analisis', models.BooleanField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Maneja',
                'verbose_name_plural': 'Maneja',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Trabaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo_inv', models.IntegerField()),
                ('id_area_con', models.IntegerField()),
                ('estado_estudio', models.BooleanField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Trabaja',
                'verbose_name_plural': 'Trabaja',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Departamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Pais')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
