# Generated by Django 2.2.3 on 2020-10-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='DepartmentU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'DepartamentoU',
                'verbose_name_plural': 'DepartamentosU',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_inst', models.CharField(max_length=30)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.City')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='InvestigationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('foundation_date', models.DateField()),
                ('departmentU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.DepartmentU')),
            ],
            options={
                'verbose_name': 'Grupo de investigación',
                'verbose_name_plural': 'Grupos de investigación',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Area del conocimiento',
                'verbose_name_plural': 'Areas del conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_director_student', models.BooleanField(default=False)),
                ('is_director_gi', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Institution')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='WorksInvestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_status', models.BooleanField()),
                ('inv_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.InvestigationGroup')),
                ('know_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.KnowledgeArea')),
            ],
            options={
                'verbose_name': 'Trabaja',
                'verbose_name_plural': 'Trabaja',
            },
        ),
        migrations.CreateModel(
            name='WorksDepartm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboral_category', models.CharField(max_length=50)),
                ('laboral_state', models.BooleanField(default=False)),
                ('departmentU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.DepartmentU')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Professor')),
            ],
            options={
                'verbose_name': 'Labora',
                'verbose_name_plural': 'Labora',
            },
        ),
        migrations.CreateModel(
            name='IsMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membershio_status', models.BooleanField()),
                ('inv_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.InvestigationGroup')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Professor')),
            ],
            options={
                'verbose_name': 'Es Miembro',
                'verbose_name_plural': 'Son Miembros',
            },
        ),
        migrations.CreateModel(
            name='InvestigationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('know_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.KnowledgeArea')),
            ],
            options={
                'verbose_name': 'Linea de investigación',
                'verbose_name_plural': 'Lineas de investigación',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Institution')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_state', models.BooleanField()),
                ('inv_line', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.InvestigationLine')),
                ('professor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Professor')),
            ],
            options={
                'verbose_name': 'Maneja',
                'verbose_name_plural': 'Maneja',
            },
        ),
        migrations.CreateModel(
            name='Directs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_state', models.BooleanField()),
                ('inv_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.InvestigationGroup')),
                ('professor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Professor')),
            ],
            options={
                'verbose_name': 'Dirige',
                'verbose_name_plural': 'Dirige',
            },
        ),
        migrations.AddField(
            model_name='departmentu',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Faculty'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Country')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_information_management_app.Department'),
        ),
    ]
