# Generated by Django 2.2.3 on 2020-09-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo_investigacion',
            fields=[
                ('id_grupo_investigacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_institucion', models.IntegerField()),
                ('id_area_conocimiento', models.IntegerField()),
                ('id_director', models.IntegerField()),
                ('nombre_grupo_inv', models.CharField(max_length=50)),
                ('anyo_fundacion', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
