# Generated by Django 2.2.3 on 2020-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0002_grupo_investigacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo_investigacion',
            options={'verbose_name': 'Grupo de investigación', 'verbose_name_plural': 'Grupos de investigación'},
        ),
        migrations.AlterField(
            model_name='grupo_investigacion',
            name='anyo_fundacion',
            field=models.DateField(),
        ),
    ]
