# Generated by Django 2.2.3 on 2020-10-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0002_auto_20201016_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('es_interno', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
