# Generated by Django 2.2.3 on 2020-09-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0003_auto_20200920_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo_investigacion',
            old_name='anyo_fundacion',
            new_name='fundacion_grupo',
        ),
        migrations.RemoveField(
            model_name='grupo_investigacion',
            name='id_area_conocimiento',
        ),
        migrations.RemoveField(
            model_name='grupo_investigacion',
            name='id_director',
        ),
    ]
