# Generated by Django 2.2.3 on 2020-10-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0003_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineainvestigacion',
            name='id_area_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.AreaConocimiento'),
        ),
    ]
