# Generated by Django 2.2.3 on 2020-10-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0004_auto_20201017_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineainvestigacion',
            old_name='id_area_con',
            new_name='area_con',
        ),
    ]
