# Generated by Django 2.2.3 on 2020-10-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0005_ciudad_departamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grupo_investigacion',
            new_name='GrupoInvestigacion',
        ),
        migrations.RenameField(
            model_name='grupoinvestigacion',
            old_name='fundacion_grupo',
            new_name='fecha_fundacion',
        ),
        migrations.RenameField(
            model_name='grupoinvestigacion',
            old_name='id_grupo_investigacion',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='grupoinvestigacion',
            old_name='nombre_grupo_inv',
            new_name='nombre',
        ),
    ]
