# Generated by Django 2.2.3 on 2020-10-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0006_auto_20201017_1714'),
        ('d_information_management_app', '0006_auto_20201017_1725'),
    ]

    operations = [
    ]
