# Generated by Django 2.2.3 on 2020-10-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0009_auto_20201018_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Institucion')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Facultad')),
            ],
            options={
                'verbose_name': 'DepartamentoU',
                'verbose_name_plural': 'DepartamentosU',
            },
        ),
    ]
