# Generated by Django 2.2.3 on 2020-10-23 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0010_departamentou_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_laboral', models.CharField(max_length=50)),
                ('estado_laboral', models.BooleanField(default=False)),
                ('departamentoU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.DepartamentoU')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Profesor')),
            ],
            options={
                'verbose_name': 'Labora',
                'verbose_name_plural': 'Labora',
            },
        ),
        migrations.CreateModel(
            name='es_miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_membresia', models.BooleanField()),
                ('grupo_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.GrupoInvestigacion')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Profesor')),
            ],
            options={
                'verbose_name': 'Es Miembro',
                'verbose_name_plural': 'Son Miembros',
            },
        ),
        migrations.CreateModel(
            name='Dirige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.GrupoInvestigacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Profesor')),
                ('estado_direccion', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Dirige',
                'verbose_name_plural': 'Dirige',
            },
        ),
        migrations.CreateModel(
            name='Maneja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_linea_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.LineaInvestigacion')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Profesor')),
                ('estado_analisis', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Maneja',
                'verbose_name_plural': 'Maneja',
            },
        ),
    ]
