# Generated by Django 2.2.3 on 2020-10-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_information_management_app', '0011_es_miembro_labora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirige',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='dirige',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='maneja',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='maneja',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='maneja',
            name='id_linea_inv',
        ),
        migrations.RemoveField(
            model_name='maneja',
            name='id_profesor',
        ),
        migrations.AddField(
            model_name='maneja',
            name='linea_inv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.LineaInvestigacion'),
        ),
        migrations.AddField(
            model_name='maneja',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Profesor'),
        ),
        migrations.AlterField(
            model_name='dirige',
            name='grupo_inv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.GrupoInvestigacion'),
        ),
        migrations.AlterField(
            model_name='dirige',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_information_management_app.Profesor'),
        ),
    ]
