# Generated by Django 2.2.3 on 2020-10-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default=3113425897, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.CharField(default=1061785746, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
